### ISSUE TITLE
Feature request: RMarkdown (.Rmd) support

### ISSUE THREAD

**Issue by jacob-long** [MikhailArkhipov/vscode-r#3]
By "support," I mostly just mean syntax highlighting and the ability to send code from code chunks to the active R session.

**Comment by MikhailArkhipov** [comment]
Short term you can add

```json
    "files.associations": {
        "*.rmd": "markdown"
    }
```

so RMD will be at least treated as regular markdown with syntax coloring and preview. Unfortunately, VS Code does not allow implementation of colorizers in code as VS does and does not have direct ability to support 'stitching' of multiple text buffers in different languages into a single view (aka "projection"). However, perhaps I can borrow some technic from HTML colors since it does support CSS and JavaScript while technically they are different languages from the HTML itself.

**Comment by MikhailArkhipov** [comment]
https://github.com/MikhailArkhipov/vscode-r/releases/tag/0.0.2

**Comment by paulklemm** [comment]
I don't know if I messed up setting everything up, but I cannot see how RMarkdown is supported right now. With the default association being standard markdown, I do not have any syntax highlighting whatsoever. https://github.com/MikhailArkhipov/vscode-r/blob/871e4f07476bb4f068feed25be79c17b62b11e8d/src/VSCode/src/extension.ts#L28)

![image](https://user-images.githubusercontent.com/2169489/52847018-63c88e00-310b-11e9-9c01-893de0604bec.png)

Also, there is no autocomplete or other vscode-r features enabled. Switching the syntax to standard R is also not an option, since the many errors do not allow any productive work.

![image](https://user-images.githubusercontent.com/2169489/52847234-eb160180-310b-11e9-9612-54021b802c83.png)

Is there any way for properly including auto-complete as well as syntax highlighting?

**Comment by Hong-Revo** [comment]
@paulklemm you can get syntax highlighting if you use \`\`\`r instead of \`\`\`{r, …}. Unfortunately this means rmarkdown won't execute the code when you knit it, so it doesn't really solve the underlying issue.

![image](https://user-images.githubusercontent.com/11328890/52848986-2a703c80-3164-11e9-9653-fb02313b1213.png)

Interestingly, you can also do \`\`\`python and it will colorise according to Python rules... maybe this is something that could be added to the markdown code, to support \`\`\`{foo, …} syntax as well.

**Comment by paulklemm** [comment]
> you can get syntax highlighting if you use ```r instead of ```{r, …}. Unfortunately this means rmarkdown won't execute the code when you knit it, so it doesn't really solve the underlying issue.

Unfortunately, this is not an option for me.

One way to go at least for the syntax highlighting is using the one from the `Ikuyadeu.r` package https://github.com/Ikuyadeu/vscode-R/blob/84808095948287503db667602a61c74b963968a2/syntax/Markdown%20Redcarpet.tmLanguage

**Comment by MikhailArkhipov** [comment]
RMD support is fairly basic. The extension associates RMD with embedded markdown editor so you can have preview tab. Like this

![image](https://user-images.githubusercontent.com/12820357/52878404-63cb8c80-3111-11e9-91aa-62beeab86c18.png)

Second, it adds Ctrl+Enter support to send any line from RMD to the R console:

![image](https://user-images.githubusercontent.com/12820357/52878484-99707580-3111-11e9-876d-dc8b712012e3.png).

There is no way to have auto-complete for R inside markdown since VS Code editor has no facilities for embedded languages or stitched views with multiple languages like VS IDE.

Triple-tick R with arguments is RStudio syntax and not part of the standard markdown so VS Code markdown editor does not support it. VS Code is not as extensible as, say, big VS where pretty much anything can be replaced or customized.

As above, this was about _By "support," I mostly just mean syntax highlighting and the ability to send code from code chunks to the active R session._
