### ISSUE TITLE
R Tools incompatible with .NET 6.0

### ISSUE THREAD

**Issue by Pinatata** [MikhailArkhipov/vscode-r#58]
Microsoft recently released preview builds of .NET 6.0. R Tools produced the following errors when only .NET 6.0 Preview 2 was installed on my machine:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      6.0.0-preview.2.21154.6 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=arm64&rid=osx.11.0-arm64
[Info  - 10:58:33 PM] Connection to server got closed. Server will restart.
```

**Comment by MikhailArkhipov** [comment]
It is not really possible to have 5.0 build to be forward compatible with 6.0. I can't build for 6.0 since I don't want to force people installing preview frameworks. I believe it is possible to have both 5.0 and 6.0 installed though. 

There is only one C# solution for the language server so building it for both 6.x and 5.x would involve custom build system outside VS, like on DevOps which I don't have.

**Comment by MikhailArkhipov** [comment]
Closing for now as there is no plan to support preview builds.
